import { VocabularyItem } from "@/types/vocabulary";

export const SEED_VOCABULARY: VocabularyItem[] = [
  // --- B1 / B1+ Connectors & Transitions ---
  {
    id: "v1",
    word: "actually",
    translationPt: "na verdade / realmente",
    definitionEn: "in fact or really",
    partOfSpeech: "adverb",
    cefrLevel: "B1",
    exampleSentence: "Actually, I prefer having team syncs in the morning.",
    contextNote: "/ˈæktʃu.ə.li/",
  },
  {
    id: "v2",
    word: "although",
    translationPt: "embora / apesar de que",
    definitionEn: "despite the fact that",
    partOfSpeech: "connector",
    cefrLevel: "B1+",
    exampleSentence: "Although it was raining, we went for a run.",
    contextNote: "/ɔːlˈðoʊ/",
  },
  {
    id: "v3",
    word: "meanwhile",
    translationPt: "enquanto isso / ao mesmo tempo",
    definitionEn: "until something expected happens, or while something else is happening",
    partOfSpeech: "connector",
    cefrLevel: "B1+",
    exampleSentence: "The server is rebooting; meanwhile, let's review the code diff.",
    contextNote: "/ˈmiːn.waɪl/",
  },
  {
    id: "v4",
    word: "furthermore",
    translationPt: "além disso / ademais",
    definitionEn: "in addition to what has just been said",
    partOfSpeech: "connector",
    cefrLevel: "B2",
    exampleSentence: "The design is elegant; furthermore, it reduces page load by 40%.",
    contextNote: "/ˌfɝː.ðɚˈmɔːr/",
  },

  // --- Phrasal Verbs ---
  {
    id: "v5",
    word: "figure out",
    translationPt: "descobrir / resolver / entender",
    definitionEn: "to understand or find the solution to a problem",
    partOfSpeech: "phrasal_verb",
    cefrLevel: "B1",
    exampleSentence: "We need to figure out how to optimize this API latency.",
    contextNote: "/ˈfɪɡ.jɚ aʊt/",
  },
  {
    id: "v6",
    word: "come up with",
    translationPt: "ter uma ideia / bolar / propor",
    definitionEn: "to suggest or think of an idea or plan",
    partOfSpeech: "phrasal_verb",
    cefrLevel: "B1+",
    exampleSentence: "She came up with a brilliant approach for the onboarding flow.",
    contextNote: "/kʌm ʌp wɪð/",
  },
  {
    id: "v7",
    word: "look forward to",
    translationPt: "estar ansioso por / aguardar com expectativa",
    definitionEn: "to feel pleased and excited about something that is going to happen",
    partOfSpeech: "phrasal_verb",
    cefrLevel: "B1",
    exampleSentence: "I look forward to discussing the release roadmap tomorrow.",
    contextNote: "/lʊk ˈfɔːr.wɚd tuː/",
  },
  {
    id: "v8",
    word: "run out of",
    translationPt: "ficar sem / esgotar",
    definitionEn: "to have no more of something left",
    partOfSpeech: "phrasal_verb",
    cefrLevel: "B1",
    exampleSentence: "We ran out of server memory during the load test.",
    contextNote: "/rʌn aʊt əv/",
  },

  // --- Adjectives & Precision Vocabulary ---
  {
    id: "v9",
    word: "exhausted",
    translationPt: "extremamente cansado / exausto",
    definitionEn: "very tired or having no energy left",
    partOfSpeech: "adjective",
    cefrLevel: "B1",
    exampleSentence: "After 8 hours of intense coding, I was completely exhausted.",
    contextNote: "/ɪɡˈzɔː.stɪd/",
  },
  {
    id: "v10",
    word: "seamless",
    translationPt: "perfeito / fluido / sem atrito",
    definitionEn: "happening without any sudden interruption or difficulty",
    partOfSpeech: "adjective",
    cefrLevel: "B2",
    exampleSentence: "The transition between audio models was completely seamless.",
    contextNote: "/ˈsiːm.ləs/",
  },
  {
    id: "v11",
    word: "worthwhile",
    translationPt: "que vale a pena / compensador",
    definitionEn: "useful, important, or good enough to be worth spending time or money on",
    partOfSpeech: "adjective",
    cefrLevel: "B1+",
    exampleSentence: "It is worthwhile to write automated unit tests for critical paths.",
    contextNote: "/ˌwɝːθˈwaɪl/",
  },
  {
    id: "v12",
    word: "straightforward",
    translationPt: "direto / simples / descomplicado",
    definitionEn: "easy to understand or simple",
    partOfSpeech: "adjective",
    cefrLevel: "B1+",
    exampleSentence: "The API documentation is clear and straightforward.",
    contextNote: "/ˌstreɪtˈfɔːr.wɚd/",
  },

  // --- Foundational A1 / A2 Vocabulary (Beginner & Child Track) ---
  {
    id: "v13",
    word: "awesome",
    translationPt: "incrível / sensacional",
    definitionEn: "extremely good or impressive",
    partOfSpeech: "adjective",
    cefrLevel: "A2",
    exampleSentence: "Your pronunciation is awesome today!",
    contextNote: "/ˈɑː.səm/",
  },
  {
    id: "v14",
    word: "daily routine",
    translationPt: "rotina diária",
    definitionEn: "the things that you do every day at the same time",
    partOfSpeech: "idiom",
    cefrLevel: "A1",
    exampleSentence: "My daily routine starts with coffee and listening to English podcasts.",
    contextNote: "/ˈdeɪli ruːˈtiːn/",
  },
  {
    id: "v15",
    word: "improve",
    translationPt: "melhorar / aprimorar",
    definitionEn: "to get better or to make something better",
    partOfSpeech: "verb",
    cefrLevel: "A2",
    exampleSentence: "Practicing 15 minutes a day will improve your speaking speed.",
    contextNote: "/ɪmˈpruːv/",
  },
  {
    id: "v16",
    word: "reliable",
    translationPt: "confiável / seguro",
    definitionEn: "can be trusted or believed",
    partOfSpeech: "adjective",
    cefrLevel: "B1",
    exampleSentence: "We need a reliable database backup strategy.",
    contextNote: "/rɪˈlaɪ.ə.bəl/",
  },

  // --- High-Impact Conversational Chunks & Idioms ---
  {
    id: "v17",
    word: "hit the ground running",
    translationPt: "começar com força total / iniciar sem perder tempo",
    definitionEn: "to start something with great energy and speed",
    partOfSpeech: "idiom",
    cefrLevel: "B2",
    exampleSentence: "With your onboarding done, you can hit the ground running on the new sprint.",
    contextNote: "/hɪt ðə ɡraʊnd ˈrʌn.ɪŋ/",
  },
  {
    id: "v18",
    word: "touch base with someone",
    translationPt: "fazer um alinhamento rápido / trocar uma ideia",
    definitionEn: "to briefly talk with someone to make sure everyone is updated",
    partOfSpeech: "idiom",
    cefrLevel: "B1+",
    exampleSentence: "Let's touch base tomorrow morning before the release.",
    contextNote: "/tʌtʃ beɪs wɪð/",
  },
  {
    id: "v19",
    word: "on the same page",
    translationPt: "na mesma sintonia / alinhados",
    definitionEn: "in agreement or having the same understanding",
    partOfSpeech: "idiom",
    cefrLevel: "B1",
    exampleSentence: "I just want to ensure we are all on the same page regarding the timeline.",
    contextNote: "/ɒn ðə seɪm peɪdʒ/",
  },
  {
    id: "v20",
    word: "cut to the chase",
    translationPt: "ir direto ao ponto",
    definitionEn: "to talk about the important parts without wasting time",
    partOfSpeech: "idiom",
    cefrLevel: "B2",
    exampleSentence: "Let's cut to the chase and discuss the root cause of the bug.",
    contextNote: "/kʌt tuː ðə tʃeɪs/",
  },
  {
    id: "v21",
    word: "call it a day",
    translationPt: "encerrar o trabalho por hoje",
    definitionEn: "to stop what you are doing because you have done enough",
    partOfSpeech: "idiom",
    cefrLevel: "B1",
    exampleSentence: "We solved the main issue, so let's call it a day.",
    contextNote: "/kɔːl ɪt ə deɪ/",
  },
];
